Proyecto_Integrador/Proyecto_Integrador/Models/PROVEEDOR.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVEEDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROVEEDOR()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int IDE_PROV { get; set; }
        public string NOM_PROV { get; set; }
        public string DIR_PROV { get; set; }
        public string FON_PROV { get; set; }
        public string COR_PROV { get; set; }
        public Nullable<int> IDE_DIS { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}

Proyecto_Integrador/Proyecto_Integrador/Controllers/ProveedorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Proyecto_Integrador.Model;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;

namespace Proyecto_Integrador.Controllers
{
    public class ProveedorController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        // GET: Producto
        public ActionResult Index()
        {
            return View();
        }

        List<Proveedor> listProveedor()
        {
            List<Proveedor> aProveedor = new List<Proveedor>();
            SqlCommand cmd = new SqlCommand("SP_LISTADOPROVEEDOR", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aProveedor.Add(new Proveedor()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    direccion = dr[2].ToString(),
                    telefono = dr[3].ToString(),
                    correo = dr[4].ToString(),
                    distrito = dr[5].ToString()

                });

            }
            cn.Close();
            return aProveedor;
        }

        List<ProveedorO> listProveedorO()
        {
            List<ProveedorO> aProveedorO = new List<ProveedorO>();
            SqlCommand cmd = new SqlCommand("SP_LISTAPROVEEDOR", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aProveedorO.Add(new ProveedorO()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    direccion = dr[2].ToString(),
                    telefono = dr[3].ToString(),
                    correo = dr[4].ToString(),
                    distrito = int.Parse(dr[5].ToString())

                });

            }
            cn.Close();
            return aProveedorO;
        }

        public ActionResult listadoProveedores()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            return View(listProveedor());
        }



        List<Distrito> listDistritos()
        {
            List<Distrito> aDistrito = new List<Distrito>();
            SqlCommand cmd = new SqlCommand("SP_LISTADISTRITO", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aDistrito.Add(new Distrito()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString()
                });

            }
            cn.Close();
            return aDistrito;
        }

        public ActionResult eliminarProveedor(int id)
        {
            ProveedorO objP = listProveedorO().Where(p => p.codigo == id).FirstOrDefault();
            ViewBag.mensaje = "";
            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_ELIMINAPROVEEDOR", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ide", objP.codigo);
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.mensaje = x.ToString() + " Proveedor Eliminado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.mensaje = ex.Message;
                tr.Rollback();
            }
            finally
            {
                cn.Close();
            }
            return RedirectToAction("listadoProveedores");
        }


        public ActionResult modificarProveedor(int id)
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            ProveedorO objP = listProveedorO().Where(p => p.codigo == id).FirstOrDefault();
            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            return View(objP);
        }

        [HttpPost]
        public ActionResult modificarProveedor(ProveedorO objP)
        {
            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            ViewBag.Success = "";
            ViewBag.Error = "";
            ViewBag.Info = "";

            

            if (objP.nombre == null)
            {
                ViewBag.Info = "Ingrese el nombre";
                return View(objP);
            }

            if (objP.direccion == null)
            {
                ViewBag.Info = "Ingrese la direccion";
                return View(objP);
            }

            if (objP.telefono == null)
            {
                ViewBag.Info = "Ingrese el telefono";
                return View(objP);
            }

            if (objP.correo == null)
            {
                ViewBag.Info = "Ingrese el correo";
                return View(objP);
            }

            if (objP.distrito == 0)
            {
                ViewBag.Info = "Seleccione el distrito";
                return View(objP);
            }

            if (!ModelState.IsValid)
            {
                //ViewBag.Info = "Revisar las validaciones";
                return View(objP);
            }

            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_ACTUALIZAPROVEEDOR", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ide", objP.codigo);
                cmd.Parameters.AddWithValue("@nom", objP.nombre);
                cmd.Parameters.AddWithValue("@dir_prov", objP.direccion);
                cmd.Parameters.AddWithValue("@fon_prov", objP.telefono);
                cmd.Parameters.AddWithValue("@cor_prov", objP.correo);
                cmd.Parameters.AddWithValue("@ide_dis", objP.distrito);
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = x.ToString() + " Proveedor Actualizado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                tr.Rollback();
            }
            finally
            {
                cn.Close();
            }

            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            return View(objP);
        }


        public ActionResult registrarProveedor()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            return View(new ProveedorO());
        }

        [HttpPost]
        public ActionResult registrarProveedor(ProveedorO objP)
        {
            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            ViewBag.Success = "";
            ViewBag.Error = "";
            ViewBag.Info = "";

            

            if (objP.nombre == null)
            {
                ViewBag.Info = "Ingrese el nombre";
                return View(objP);
            }

            if (objP.direccion == null)
            {
                ViewBag.Info = "Ingrese la direccion";
                return View(objP);
            }

            if (objP.telefono == null)
            {
                ViewBag.Info = "Ingrese el telefono";
                return View(objP);
            }

            if (objP.correo == null)
            {
                ViewBag.Info = "Ingrese el correo";
                return View(objP);
            }

            if (objP.distrito == 0)
            {
                ViewBag.Info = "Seleccione el distrito";
                return View(objP);
            }

            if (!ModelState.IsValid)
            {
                //ViewBag.Info = "Revisar las validaciones";
                return View(objP);
            }

            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_NUEVOPROVEEDOR", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@nom", objP.nombre);
                cmd.Parameters.AddWithValue("@dir_prov", objP.direccion);
                cmd.Parameters.AddWithValue("@fon_prov", objP.telefono);
                cmd.Parameters.AddWithValue("@cor_prov", objP.correo);
                cmd.Parameters.AddWithValue("@ide_dis", objP.distrito);
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = x.ToString() + " Proveedor Registrado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                tr.Rollback();
            }
            finally
            {
                cn.Close();
            }

            ViewBag.distrito = new SelectList(listDistritos(), "codigo", "nombre");
            return View(objP);

        }

    }
}

Proyecto_Integrador/Proyecto_Integrador/Views/Proveedor/listadoProveedores.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Proveedor>

@{
    ViewBag.Title = "listadoProveedores";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<p>
    @Html.ActionLink("Nuevo Proveedor", "registrarProveedor", null, new { @class = "btn btn-success" })
</p>
<table class="table" style="width: 98%;max-width: 100%;margin-bottom: 20px;background-color: white;margin-left: -1px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.distrito)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.distrito)
            </td>
            <td>
                @Html.ActionLink("Actualizar", "modificarProveedor", new { id = item.codigo }, new { @class = "btn btn-info" })
                @Html.ActionLink("Eliminar", "eliminarProveedor", new { id = item.codigo }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>


<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Proveedor/modificarProveedor.cshtml
@model Proyecto_Integrador.Model.ProveedorO

@{
    ViewBag.Title = "modificarProveedor";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

@using (Html.BeginForm("modificarProveedor", "Proveedor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="background-color: white; width: 98%;">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("distrito", (SelectList)ViewBag.distrito,
               "(Seleccione Distrito)", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listadoProveedores", null, new { @class = "btn btn-info" })
</div>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Proveedor/registrarProveedor.cshtml
@model Proyecto_Integrador.Model.ProveedorO

@{
    ViewBag.Title = "registrarProveedor";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

@using (Html.BeginForm("registrarProveedor", "Proveedor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="background-color: white; width: 98%;">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.distrito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">

                @Html.DropDownListFor(model => model.distrito, ViewBag.distrito as SelectList, "Seleccione Distrito", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listadoProveedores", null, new { @class = "btn btn-info" })
</div>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>