Proyecto_Integrador/Proyecto_Integrador/Models/SERVICIO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int IDE_SER { get; set; }
        public string NOM_SER { get; set; }
        public string DES_SER { get; set; }
        public Nullable<System.DateTime> FEC_SER { get; set; }
        public Nullable<decimal> PRE_SER { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_CLI { get; set; }
        public Nullable<int> IDE_EMP { get; set; }
        public string IMG_SER { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}

Proyecto_Integrador/Proyecto_Integrador/Controllers/ServicioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using Proyecto_Integrador.Model;
using System.Data.SqlClient;
using System.Configuration;
using System.Data;
namespace Proyecto_Integrador.Controllers
{
    public class ServicioController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        // GET: Servicio
        public ActionResult Index()
        {
            return View();
        }

        List<Servicios> listServicios()
        {
            List<Servicios> aServicios = new List<Servicios>();
            SqlCommand cmd = new SqlCommand("SP_LISTASERVICIO", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aServicios.Add(new Servicios()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    nombre = dr[1].ToString(),
                    descripcion = dr[2].ToString(),
                    fechaservicio = DateTime.Parse(dr[3].ToString()),
                    precio = double.Parse(dr[4].ToString())
                });

            }
            cn.Close();
            return aServicios;
        }

        public ActionResult listadoServicios()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            return View(listServicios());
        }

        public ActionResult eliminarServicio(int id)
        {
            Servicios objP = listServicios().Where(p => p.codigo == id).FirstOrDefault();
            ViewBag.Success = "";
            ViewBag.Error = "";
            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_ELIMINASERVICIO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ide_ser", objP.codigo);
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = x.ToString() + " Servicio Eliminado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                tr.Rollback();
                return RedirectToAction("listadoServicios");
            }
            finally
            {
                cn.Close();
            }
            return RedirectToAction("listadoServicios");
        }


        public ActionResult modificarServicio(int id)
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            Servicios objS = listServicios().Where(p => p.codigo == id).FirstOrDefault();
            return View(objS);
        }

        [HttpPost]
        public ActionResult modificarServicio(Servicios objS, HttpPostedFileBase f)
        {
            ViewBag.Success = "";
            ViewBag.Error = "";
            ViewBag.Info = "";

            
            if (objS.nombre == null)
            {
                ViewBag.Info = "Ingrese el nombre";
                return View(objS);
            }
            if (objS.descripcion == null)
            {
                ViewBag.Info = "Ingrese la descripcion";
                return View(objS);
            }
            if (objS.fechaservicio == null)
            {
                ViewBag.Info = "Ingrese la fecha";
                return View(objS);
            }
            if (objS.precio == 0)
            {
                ViewBag.Info = "Ingrese el precio";
                return View(objS);
            }

            if (f == null)
            {
                ViewBag.Info = "Seleccione una imagen";
                return View(objS);
            }
            if (Path.GetExtension(f.FileName) != ".jpg")
            {
                ViewBag.Info = "Debe ser .JPG";
                return View(objS);
            }
            if (!ModelState.IsValid)
            {
                //ViewBag.Info = "Revisar las validaciones";
                return View(objS);
            }


            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_ACTUALIZASERVICIO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ide_ser", objS.codigo);
                cmd.Parameters.AddWithValue("@nom_ser", objS.nombre);
                cmd.Parameters.AddWithValue("@des_ser", objS.descripcion);
                cmd.Parameters.AddWithValue("@fec_ser", objS.fechaservicio);
                cmd.Parameters.AddWithValue("@pre_ser", objS.precio);
                cmd.Parameters.AddWithValue("@img_ser", "~/fotos_servicios/" + Path.GetFileName(f.FileName));
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = x.ToString() + " Servicio Actualizado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                tr.Rollback();
            }
            finally
            {
                cn.Close();
            }

            f.SaveAs(Path.Combine(Server.MapPath("~/fotos_servicios/"),
               Path.GetFileName(f.FileName)));

            return View(objS);
        }


        public ActionResult registrarServicio()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            return View(new Servicios());
        }

        [HttpPost]
        public ActionResult registrarServicio(Servicios objS, HttpPostedFileBase f)
        {

            ViewBag.Success = "";
            ViewBag.Error = "";
            ViewBag.Info = "";

            if (objS.nombre == null)
            {
                ViewBag.Info = "Ingrese el nombre";
                return View(objS);
            }
            if (objS.descripcion == null)
            {
                ViewBag.Info = "Ingrese la descripcion";
                return View(objS);
            }
            if (objS.fechaservicio == null)
            {
                ViewBag.Info = "Ingrese la fecha";
                return View(objS);
            }
            if (objS.precio == 0)
            {
                ViewBag.Info = "Ingrese el precio";
                return View(objS);
            }

            if (f == null)
            {
                ViewBag.Info = "Seleccione una imagen";
                return View(objS);
            }
            if (Path.GetExtension(f.FileName) != ".jpg")
            {
                ViewBag.Info = "Debe ser .JPG";
                return View(objS);
            }
            if (!ModelState.IsValid)
            {
                //ViewBag.Info = "Revisar las validaciones";
                return View(objS);
            }
            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {
                SqlCommand cmd = new SqlCommand("SP_NUEVOSERVICIO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                //cmd.Parameters.AddWithValue("@ide_ser", objS.codigo);
                cmd.Parameters.AddWithValue("@nom_ser", objS.nombre);
                cmd.Parameters.AddWithValue("@des_ser", objS.descripcion);
                cmd.Parameters.AddWithValue("@fec_ser", objS.fechaservicio);
                cmd.Parameters.AddWithValue("@pre_ser", objS.precio);
                cmd.Parameters.AddWithValue("@img_ser", "~/fotos_servicios/" + Path.GetFileName(f.FileName));
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = x.ToString() + " Servicio Registrado..!!!";
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                tr.Rollback();
            }
            finally
            {
                cn.Close();
            }


            f.SaveAs(Path.Combine(Server.MapPath("~/fotos_servicios/"),
                Path.GetFileName(f.FileName)));

            return View(objS);
            //return View("~/Views/Servicio/registrarServicio.cshtml");
        }
    }
}

Proyecto_Integrador/Proyecto_Integrador/Views/Servicio/listadoServicios.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Servicios>

@{
    ViewBag.Title = "listadoServicios";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

@*<h2>listadoServicios</h2>*@

<p>
    @Html.ActionLink("Nuevo Servicio", "registrarServicio", null, new { @class = "btn btn-success" })
</p>
<table class="table" style="width: 98%;max-width: 100%;margin-bottom: 20px;background-color: white;margin-left: -1px;">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechaservicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.foto)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechaservicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.foto)
                </td>*@
            <td>
                @Html.ActionLink("Actualizar", "modificarServicio", new { id = item.codigo }, new { @class = "btn btn-info" })
                @Html.ActionLink("Eliminar", "eliminarServicio", new { id = item.codigo }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Servicio/modificarServicio.cshtml
@model Proyecto_Integrador.Model.Servicios

@{
    ViewBag.Title = "modificarServicio";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-20px">Modificar Servicio</h2>
@using (Html.BeginForm("modificarServicio", "Servicio", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal" style="background-color: white; width: 98%;">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fechaservicio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.fechaservicio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.fechaservicio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3">
                    @Html.TextBox("f", "", new { type = "file" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Actualizar" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
}


<div>
    @Html.ActionLink("Regresar", "listadoServicios", null, new { @class = "btn btn-info" })
</div>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Servicio/registrarServicio.cshtml
@model Proyecto_Integrador.Model.Servicios

@{
    ViewBag.Title = "registrarServicio";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-20px">registrarServicio</h2>

@using (Html.BeginForm("registrarServicio", "Servicio", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="background-color: white; width: 98%;">
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaservicio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.fechaservicio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaservicio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.TextBox("f", "", new { type = "file" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-3">
                <input type="submit" value="Registrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "listadoServicios", null, new { @class = "btn btn-success" })
</div>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>