Proyecto_Integrador/Proyecto_Integrador/Models/PEDIDO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.DETALLE = new HashSet<DETALLE>();
            this.TRACKING = new HashSet<TRACKING>();
        }
    
        public int IDE_PED { get; set; }
        public System.DateTime FEC_PED { get; set; }
        public Nullable<System.DateTime> FEN_PED { get; set; }
        public string ENV_PED { get; set; }
        public Nullable<int> CAN_PED { get; set; }
        public string DES_PED { get; set; }
        public string REF_PED { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> IDE_DIS { get; set; }
        public Nullable<int> IDE_CLI { get; set; }
        public Nullable<int> IDE_EMP { get; set; }
        public Nullable<int> IDE_SER { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE> DETALLE { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual EMPLEADO EMPLEADO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRACKING> TRACKING { get; set; }
    }
}

Proyecto_Integrador/Proyecto_Integrador/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using Proyecto_Integrador.Model;

namespace Proyecto_Integrador.Controllers
{
    public class PedidoController : Controller
    {
        SqlConnection cn = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        // GET: Pedido
        public ActionResult Index()
        {
            return View();
        }

        //lista de pedidos
        List<Pedido> listPedidos()
        {
            int id = int.Parse(Session["idUser"].ToString());
            List<Pedido> aPedidos = new List<Pedido>();
            SqlCommand cmd = new SqlCommand("SP_LISTAPEDIDOTRACKING", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ide_usu", id);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aPedidos.Add(new Pedido()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    fechapedido = dr[1].ToString(),
                    //descripcion = dr[2].ToString(),
                    cantidad = int.Parse(dr[2].ToString()),
                    //precio = double.Parse(dr[4].ToString()),
                    //monto = double.Parse(dr[5].ToString()),
                    cliente = dr[3].ToString(),
                    tracking = dr[4].ToString(),
                    //foto = dr[8].ToString()
                });

            }
            cn.Close();
            return aPedidos;
        }

        public ActionResult ListadoPedidos()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            return View(listPedidos());

        }


        List<Pedido> listPedidosDetalle(int id)
        {
            
            List<Pedido> aPedidos = new List<Pedido>();
            SqlCommand cmd = new SqlCommand("SP_LISTAPEDIDOTRACKING_DET", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.AddWithValue("@ide_ped", id);
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aPedidos.Add(new Pedido()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    fechapedido = dr[1].ToString(),
                    descripcion = dr[2].ToString(),
                    cantidad = int.Parse(dr[3].ToString()),
                    precio = double.Parse(dr[4].ToString()),
                    monto = double.Parse(dr[5].ToString()),
                    foto = dr[6].ToString()
                });

            }
            cn.Close();
            return aPedidos;
        }

        public ActionResult ListadoPedidosDetalle(int id)
        {
            return View(listPedidosDetalle(id));
        }


        List<Pedido> listdePedidos()
        {
            List<Pedido> aPedidos = new List<Pedido>();
            SqlCommand cmd = new SqlCommand("SP_LISTADOPEDIDOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aPedidos.Add(new Pedido()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    fechapedido = dr[1].ToString(),
                    //descripcion = dr[2].ToString(),
                    cantidad = int.Parse(dr[2].ToString()),
                    //precio = double.Parse(dr[4].ToString()),
                    //monto = double.Parse(dr[5].ToString()),
                    cliente = dr[3].ToString(),
                    tracking = dr[4].ToString(),
                    //foto = dr[8].ToString()
                });

            }
            cn.Close();
            return aPedidos;
        }

        public ActionResult ListadodePedidos()
        {
            ViewBag.Message = "Bienvenido(a) " + Session["User"];
            return View(listdePedidos());

        }
        public ActionResult ListadodePedidosDetalle(int id)
        {
            return View(listPedidosDetalle(id));
        }

        List<Estado> listEstados()
        {
            List<Estado> aEstados = new List<Estado>();
            SqlCommand cmd = new SqlCommand("SP_LISTAESTADOS", cn);
            cmd.CommandType = CommandType.StoredProcedure;
            cn.Open();
            SqlDataReader dr = cmd.ExecuteReader();
            while (dr.Read())
            {
                aEstados.Add(new Estado()
                {
                    codigo = int.Parse(dr[0].ToString()),
                    descripcion = dr[1].ToString()
                });

            }
            cn.Close();
            return aEstados;
        }


        public ActionResult AtenderPedido(int id)
        {
            Pedido objP = listdePedidos().Where(p => p.codigo == id).FirstOrDefault();
            ViewBag.estado = new SelectList(listEstados(), "codigo", "descripcion");
            return View(objP);
        }

        [HttpPost]
        public ActionResult AtenderPedido(Pedido objP)
        {
            ViewBag.estado = new SelectList(listEstados(), "codigo", "descripcion");
            ViewBag.Success = "";
            ViewBag.Error = "";
            ViewBag.Info = "";

            if (objP.estado == 0)
            {
                ViewBag.Info = "Seleccione el estado";
                return View(objP);
            }
            if (objP.comentario == null)
            {
                ViewBag.Info = "Ingrese el comentario";
                return View(objP);
            }

            cn.Open();
            SqlTransaction tr = cn.BeginTransaction(IsolationLevel.Serializable);
            try
            {

                SqlCommand cmd = new SqlCommand("SP_GRABARESTADOPEDIDO", cn, tr);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@ide_ped", objP.codigo);
                cmd.Parameters.AddWithValue("@ide_est", objP.estado);
                cmd.Parameters.AddWithValue("@comenta", objP.comentario);
                int x = cmd.ExecuteNonQuery();
                tr.Commit();
                ViewBag.Success = " Pedido Actualizado..!!!";

            }
            catch
            {
                ViewBag.Error = " Registro incorrecto, verificar en llenar todos los campos";
                tr.Rollback();
                cn.Close();
                ViewBag.estado = new SelectList(listEstados(), "codigo", "descripcion");
                return View("~/Views/Pedido/AtenderPedido.cshtml");
            }
            finally
            {
                cn.Close();
            }

            ViewBag.estado = new SelectList(listEstados(), "codigo", "descripcion");
            return View("~/Views/Pedido/AtenderPedido.cshtml");

        }


    }
}

Proyecto_Integrador/Proyecto_Integrador/Views/Pedido/AtenderPedido.cshtml
@model Proyecto_Integrador.Model.Pedido

@{
    ViewBag.Title = "AtenderPedido";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-10px">Atender Pedidos</h2>

@using (Html.BeginForm("AtenderPedido", "Pedido", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.EditorFor(model => model.codigo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-3">
                @Html.DropDownList("estado", (SelectList)ViewBag.estado,
                    "(Seleccione estado)", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.comentario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.EditorFor(model => model.comentario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.comentario, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink("Regresar", "ListadodePedidos", null, new { @class = "btn btn-primary" })
</div>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Pedido/ListadoPedidos.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Pedido>

@{
    ViewBag.Title = "ListadoPedidos";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-20px">Listado de Pedidos</h2>

<table class="table" style="width: 98%; background-color: white; width: 98%; margin-left: -1px; ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechapedido)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tracking)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.foto)
        </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechapedido)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>*@
            @*<td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tracking)
            </td>
            @*<td>
                <img class="foto" src="@Url.Content(item.foto)" width="30" />
            </td>*@
        <td>
            @*@Html.ActionLink("Detalle", "eliminarMascota", new { id = item.codigo }, new { @class = "btn btn-info" })*@
            @Html.ActionLink("Detalle", "ListadoPedidosDetalle" , new { id = item.codigo }, new { @class = "btn btn-success" })
        </td>
        </tr>
    }

</table>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Pedido/ListadoPedidosDetalle.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Pedido>

@{
    ViewBag.Title = "ListadoPedidosDetalle";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}
<h2 style="color:Highlight;margin-top:-20px">Listado de Pedidos Detalle</h2>

<table class="table" style="width: 98%; background-color: white; width: 98%; margin-left: -1px; ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechapedido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tracking)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechapedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.cliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tracking)
                </td>*@
            <td>
                <img class="foto" src="@Url.Content(item.foto)" width="30" />
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Regresar", "ListadoPedidos", null, new { @class = "btn btn-primary" })
</div>

Proyecto_Integrador/Proyecto_Integrador/Views/Pedido/ListadodePedidos.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Pedido>

@{
    ViewBag.Title = "ListadodePedidos";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-20px">Listado de Pedidos</h2>

<table class="table" style="width: 98%; background-color: white; width: 98%; margin-left: -1px; ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechapedido)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.monto)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tracking)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.foto)
            </th>*@
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechapedido)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.descripcion)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.precio)
                </td>*@
            @*<td>
                    @Html.DisplayFor(modelItem => item.monto)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tracking)
            </td>
            @*<td>
                    <img class="foto" src="@Url.Content(item.foto)" width="30" />
                </td>*@
        <td>

            @Html.ActionLink("Detalle", "ListadodePedidosDetalle", new { id = item.codigo }, new { @class = "btn btn-info" })
            @Html.ActionLink("Atender", "AtenderPedido", new { id = item.codigo }, new { @class = "btn btn-success" })
        </td>
        </tr>
    }

</table>

<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>

Proyecto_Integrador/Proyecto_Integrador/Views/Pedido/ListadodePedidosDetalle.cshtml
@model IEnumerable<Proyecto_Integrador.Model.Pedido>

@{
    ViewBag.Title = "ListadodePedidosDetalle";
    Layout = "~/Views/Shared/_LayoutPrincipal.cshtml";
}

<h2 style="color:Highlight;margin-top:-20px">Listado de Pedidos Detalle</h2>

<table class="table" style="width: 98%; background-color: white; width: 98%; margin-left: -1px; ">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fechapedido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        @*<th>
                @Html.DisplayNameFor(model => model.cliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tracking)
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.foto)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fechapedido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.monto)
            </td>
            @*<td>
                    @Html.DisplayFor(modelItem => item.cliente)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tracking)
                </td>*@
            <td>
                <img class="foto" src="@Url.Content(item.foto)" width="30" />
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>*@
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Regresar", "ListadodePedidos", null, new { @class = "btn btn-primary" })
</div>
<script>
    if ("@ViewBag.Error" != "")
            swal("@ViewBag.Error", "Para Continuar presione el Boton", "error");

        if ("@ViewBag.Success" != "")
            swal("@ViewBag.Success", "Para Continuar presione el Boton", "success");

        if ("@ViewBag.Info" != "")
            swal("@ViewBag.Info", "Para Continuar presione el Boton", "info");

</script>